// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsjlkhatpqozhsunqpbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzamxraGF0cHFvemhzdW5xcGJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDUyMjIsImV4cCI6MjA2MjcyMTIyMn0.qnZpQdJnHDLtd27ah8yfnoeMPQc8_NQwH7Njux46Was";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);